# Generated by Django 5.1.2 on 2024-10-24 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferreteriacore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
