# Generated by Django 5.1.2 on 2024-10-25 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferreteriacore', '0003_alter_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
