# Generated by Django 5.1.2 on 2024-10-25 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferreteriacore', '0004_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='oferta',
            field=models.BooleanField(default=True),
        ),
    ]
