# Generated by Django 5.1.2 on 2024-10-25 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferreteriacore', '0005_producto_oferta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='oferta',
            field=models.BooleanField(default=False),
        ),
    ]
