# Generated by Django 5.1.2 on 2024-10-25 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferreteriacore', '0006_alter_producto_oferta'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_web',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fondo', models.ImageField(blank=True, null=True, upload_to='web/')),
            ],
        ),
    ]
